TOKEN = 'Nzc3NTcxOTY1MTc0NTQ2NDYz.X7FYUw.mJSlEHMj1vs51nhsio1Ixs3TL7U' #TOKEN

POST_ID =  #POST ID
	

ROLES = {
    '':  , #SMILE ID AND ROLE ID
}


EXCROLLES = ()

MAX_ROLES_PER_USER = 1 #MAX ROLES FOR ONE MAN